#!/bin/bash
echo "Files ready to commit:"
echo ""
echo "✅ .github/workflows/docker-publish.yml"
echo "✅ docker-compose.prod.yml"
echo "✅ CI_CD_SETUP.md"
echo "✅ README.md"
echo ""
echo "To push manually:"
echo "1. Go to https://github.com/k4therin2/smart-home"
echo "2. Click 'Add file' > 'Create new file'"
echo "3. Name: .github/workflows/docker-publish.yml"
echo "4. Copy content from your local file"
echo "5. Commit directly to main"
echo ""
echo "Or update your GitHub token with 'workflow' scope and run: git push"
