# Build configuration for SmartHome Add-on
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-extended-build

build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20
  armv7: ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20

# Build arguments
args:
  BUILD_ARCH: "{arch}"
  BUILD_FROM: "{build_from}"

# Labels
labels:
  org.opencontainers.image.title: "SmartHome Assistant"
  org.opencontainers.image.description: "Privacy-focused, agentic smart home assistant"
  org.opencontainers.image.url: "https://github.com/k4therin2/smarthome"
  org.opencontainers.image.source: "https://github.com/k4therin2/smarthome"
  org.opencontainers.image.vendor: "k4therin2"
  org.opencontainers.image.licenses: "MIT"
